### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [Neimad971/spluty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by NeimadTL** [comment]
just added that : 
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
into the head tag.

**Comment by kenmazaika** [comment]
:+1: Thumbs up.  Looks perfect.

**Comment by NeimadTL** [comment]
cool !
